FROM typesense/typesense:27.1

# Expose Typesense port
EXPOSE 8108

# Data directory is mounted as a volume
VOLUME /data

# Typesense will be started with environment variables from Render
# Command: --data-dir /data --api-key ${TYPESENSE_API_KEY} --enable-cors
