const express = require('express');
const healthRoutes = require('./health.routes');
const authRoutes = require('./auth.routes');
const dashboardRoutes = require('./dashboard.routes');
const drugRoutes = require('./drug.routes');
const substituteRoutes = require('./substitute.routes');
const saltIntelligenceRoutes = require('./saltIntelligence.routes');

// Medicine Master routes (new system)
const medicinesRoutes = require('./medicines.routes');
const medicinesSearchRoutes = require('./medicines.search.routes');
const medicinesOverlayRoutes = require('./medicines.overlay.routes');
const medicinesIngestRoutes = require('./medicines.ingest.routes');
const medicinesImagesRoutes = require('./medicines.images.routes');
const storesRoutes = require('./stores.routes');
const onboardingRoutes = require('./onboarding.routes');
const patientsRoutes = require('./patients.routes');
const prescribersRoutes = require('./prescribers.routes');
const prescriptionsRoutes = require('./prescriptions.routes');
const inventoryRoutes = require('./inventory.routes');
const suppliersRoutes = require('./suppliers.routes');
const purchaseOrdersRoutes = require('./purchaseOrders.routes');
const grnRoutes = require('./grn.routes');
const salesRoutes = require('./sales.routes');
const reportsRoutes = require('./reports.routes');
const alertsRoutes = require('./alerts.routes');
const auditRoutes = require('./audit.routes');
const userRoutes = require('./user.routes');
const subscriptionRoutes = require('./subscription.routes');
const paymentRoutes = require('./payment.routes');
const consolidatedInvoicesRoutes = require('./consolidatedInvoices.routes');
const locationRoutes = require('./location.routes');
const scanRoutes = require('./scan.routes');
const dispenseRoutes = require('./dispense.routes');
const behavioralRoutes = require('./behavioral.routes');
const fefoRoutes = require('./fefo.routes');
const businessTypeRoutes = require('./businessType.routes');
const chatRoutes = require('./chatRoute');
const rbacRoutes = require('../rbac');
const geminiRoutes = require('../gemini.routes');
const whatsappRoutes = require('../whatsapp');
const avatarRoutes = require('../avatarRoutes');
const attachmentRoutes = require('../attachmentRoutes');
const grnAttachmentRoutes = require('../grnAttachmentRoutes');
const portalRoutes = require('../portal.routes');
const emailRoutes = require('../emailRoutes');
const loyaltyRoutes = require('../loyaltyRoutes');
const salesAnalyticsRoutes = require('../salesAnalyticsRoutes');
const gstRoutes = require('../gstRoutes');
const gdprRoutes = require('../gdprRoutes');
const cacheRoutes = require('../cacheRoutes');
const featuresRoutes = require('./features');
const platformConfigRoutes = require('../platformConfigRoutes');
const supplierInvoiceRoutes = require('./supplierInvoice.routes');
const ocrRoutes = require('./ocr.routes');

const router = express.Router();

// Mount routes
router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/drugs', drugRoutes);
router.use('/substitutes', substituteRoutes);
router.use('/salt-intelligence', saltIntelligenceRoutes);
router.use('/salt', require('./salt.routes'));

// Medicine Master routes (new system)
router.use('/medicines', medicinesRoutes);
router.use('/medicines/search', medicinesSearchRoutes);
router.use('/medicines/ingest', medicinesIngestRoutes);
router.use('/medicines', medicinesImagesRoutes);
router.use('/stores/:storeId/medicines', medicinesOverlayRoutes);
router.use('/stores', storesRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/patients', patientsRoutes);
router.use('/prescribers', prescribersRoutes);
router.use('/prescriptions', prescriptionsRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/suppliers', suppliersRoutes);
router.use('/purchase-orders', purchaseOrdersRoutes);
router.use('/grn', grnRoutes);
router.use('/sales', salesRoutes);
router.use('/reports', reportsRoutes);
router.use('/alerts', alertsRoutes);
router.use('/audit', auditRoutes);
router.use('/users', userRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/payments', paymentRoutes);
router.use('/consolidated-invoices', consolidatedInvoicesRoutes);
router.use('/supplier-invoices', supplierInvoiceRoutes);
router.use('/locations', locationRoutes);
router.use('/scan', scanRoutes);
router.use('/dispense', dispenseRoutes);
router.use('/behavioral', behavioralRoutes);
router.use('/fefo', fefoRoutes);
router.use('/business-types', businessTypeRoutes);
router.use('/chat', chatRoutes);
router.use('/rbac', rbacRoutes);
router.use('/gemini', geminiRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/avatar', avatarRoutes);
router.use('/po-attachments', attachmentRoutes);
router.use('/grn-attachments', grnAttachmentRoutes);
router.use('/portal', portalRoutes);
router.use('/email', emailRoutes);
router.use('/engage/loyalty', loyaltyRoutes);
router.use('/sales/analytics', salesAnalyticsRoutes);
router.use('/gst', gstRoutes);
router.use('/gdpr', gdprRoutes);
router.use('/cache', cacheRoutes);
router.use('/features', featuresRoutes);
router.use('/platform', platformConfigRoutes);
router.use('/margin', require('../margin.routes'));
router.use('/ocr', ocrRoutes);

module.exports = router;
