import { DocArticle } from '@/types/docs';

export const ARTICLES: DocArticle[] = [
    // ==================== GETTING STARTED ====================
    {
        id: 'initial-setup',
        title: 'System Setup & First Login',
        slug: 'getting-started/initial-setup',
        category: 'getting-started',
        tags: ['setup', 'onboarding', 'admin'],
        summary: 'Complete guide to setting up your pharmacy profile, licenses, and hardware.',
        difficulty: 'Beginner',
        estimatedTime: '10 min',
        roles: ['admin', 'owner'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/getting-started/initial-setup.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['hardware-setup', 'first-15-minutes'],
    },
    {
        id: 'hardware-setup',
        title: 'Hardware Setup & Recommended Devices',
        slug: 'getting-started/hardware-setup',
        category: 'getting-started',
        tags: ['hardware', 'printers', 'scanners', 'requirements'],
        summary: 'How to choose and configure barcode scanners, printers, and other peripherals.',
        difficulty: 'Beginner',
        estimatedTime: '8 min',
        roles: ['admin', 'it'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/getting-started/hardware-setup.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['initial-setup', 'pos-sale'],
    },
    {
        id: 'first-15-minutes',
        title: 'First 15 Minutes: Run Your First Sale',
        slug: 'getting-started/first-15-minutes',
        category: 'getting-started',
        tags: ['quickstart', 'onboarding', 'pos'],
        summary: 'A checklist to be 100% operational in 15 minutes: add a product, run a sale, print a receipt.',
        difficulty: 'Beginner',
        estimatedTime: '15 min',
        roles: ['all'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/getting-started/first-15-minutes.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['pos-sale', 'products-full-guide'],
    },

    // ==================== QUICK TASKS ====================
    {
        id: 'add-product-quick',
        title: 'Quick Add Product (Cheat-Sheet)',
        slug: 'quick-tasks/add-product-quick',
        category: 'quick-tasks',
        tags: ['inventory', 'quick', 'cheatsheet'],
        summary: 'Minimal steps to add a product in under 2 minutes.',
        difficulty: 'Beginner',
        estimatedTime: '2 min',
        roles: ['inventory', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/quick-tasks/add-product-quick.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['products-full-guide'],
    },
    {
        id: 'refund-sale',
        title: 'Refund a Sale (Cheat-Sheet)',
        slug: 'quick-tasks/refund-sale',
        category: 'quick-tasks',
        tags: ['billing', 'refund', 'quick'],
        summary: 'Fast steps to refund a sale at POS — cash or card refunds.',
        difficulty: 'Beginner',
        estimatedTime: '3 min',
        roles: ['cashier', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/quick-tasks/refund-sale.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['pos-sale', 'transactions-not-syncing'],
    },
    {
        id: 'print-label',
        title: 'Print Product Label (Quick)',
        slug: 'quick-tasks/print-label',
        category: 'quick-tasks',
        tags: ['label', 'barcode', 'quick'],
        summary: 'Print barcode labels for products and batches.',
        difficulty: 'Beginner',
        estimatedTime: '2 min',
        roles: ['inventory'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/quick-tasks/print-label.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['products-full-guide'],
    },
    {
        id: 'receive-stock',
        title: 'Receive Stock (Quick)',
        slug: 'quick-tasks/receive-stock',
        category: 'quick-tasks',
        tags: ['inventory', 'receive', 'stock'],
        summary: 'Quick workflow to receive vendor shipment and update stock.',
        difficulty: 'Beginner',
        estimatedTime: '3 min',
        roles: ['inventory'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/quick-tasks/receive-stock.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['create-po', 'batches'],
    },
    {
        id: 'process-prescription-quick',
        title: 'Process a Verified Prescription (Quick)',
        slug: 'quick-tasks/process-prescription-quick',
        category: 'quick-tasks',
        tags: ['prescription', 'quick', 'dispense'],
        summary: 'Fast steps for the pharmacy technician to fill a prescription already verified by pharmacist.',
        difficulty: 'Beginner',
        estimatedTime: '3 min',
        roles: ['pharmacist', 'technician'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/quick-tasks/process-prescription-quick.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['prescription-workflow', 'batches'],
    },

    // ==================== INVENTORY ====================
    {
        id: 'products-full-guide',
        title: 'Product Master: Fields, Categories & Tips',
        slug: 'inventory/products-full-guide',
        category: 'inventory',
        tags: ['product', 'sku', 'barcode', 'hsn', 'mrp'],
        summary: 'Complete guide to the Product Master: what each field means and how to model medicines vs non-medicines.',
        difficulty: 'Beginner',
        estimatedTime: '8 min',
        roles: ['inventory', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/inventory/products-full-guide.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['ai-forecast', 'batches'],
    },
    {
        id: 'batches',
        title: 'Batch & Expiry Management',
        slug: 'inventory/batches',
        category: 'inventory',
        tags: ['batch', 'expiry', 'lot', 'stock'],
        summary: 'How to manage batches, expiries, recalls and expired-stock workflows.',
        difficulty: 'Intermediate',
        estimatedTime: '6 min',
        roles: ['inventory', 'pharmacist'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/inventory/batches.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['products-full-guide', 'audit-logs'],
    },
    {
        id: 'ai-forecast',
        title: 'Using AI Demand Forecasting',
        slug: 'inventory/ai-forecast',
        category: 'inventory',
        tags: ['ai', 'forecasting', 'stock', 'smart'],
        summary: 'How to use AI insights to predict stockouts and optimize purchasing.',
        difficulty: 'Advanced',
        estimatedTime: '5 min',
        roles: ['manager', 'owner'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/inventory/ai-forecast.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['create-po', 'products-full-guide'],
    },
    {
        id: 'reorder-settings',
        title: 'Reorder Points & Safety Stock',
        slug: 'inventory/reorder-settings',
        category: 'inventory',
        tags: ['reorder', 'safety-stock', 'settings'],
        summary: 'How to set reorder points, safety stock and lead times for better inventory health.',
        difficulty: 'Intermediate',
        estimatedTime: '6 min',
        roles: ['inventory', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/inventory/reorder-settings.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['ai-forecast', 'standard-reports'],
    },

    // ==================== SALES & POS ====================
    {
        id: 'pos-sale',
        title: 'Running a Point of Sale (POS) Transaction',
        slug: 'billing/pos-sale',
        category: 'billing',
        tags: ['billing', 'gst', 'checkout', 'cashier'],
        summary: 'Guide to billing customers, handling GST, and accepting payments.',
        difficulty: 'Beginner',
        estimatedTime: '4 min',
        roles: ['cashier'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/billing/pos-sale.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['receipt-templates', 'products-full-guide'],
    },
    {
        id: 'receipt-templates',
        title: 'Customizing Receipt & Invoice Templates',
        slug: 'billing/receipt-templates',
        category: 'billing',
        tags: ['receipt', 'invoice', 'gst', 'templates'],
        summary: 'How to customize receipts, add logos, T&Cs, and tax breakdowns.',
        difficulty: 'Intermediate',
        estimatedTime: '6 min',
        roles: ['admin'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/billing/receipt-templates.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['pos-sale', 'e-invoicing'],
    },
    {
        id: 'returns-credits',
        title: 'Returns & Credit Notes',
        slug: 'billing/returns-credits',
        category: 'billing',
        tags: ['returns', 'refund', 'credit-note'],
        summary: 'Process returns, issue refunds, and create credit notes.',
        difficulty: 'Intermediate',
        estimatedTime: '5 min',
        roles: ['cashier', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/billing/returns-credits.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['pos-sale', 'audit-logs'],
    },

    // ==================== PRESCRIPTIONS ====================
    {
        id: 'prescription-workflow',
        title: 'Processing a New Prescription',
        slug: 'operations/prescription-workflow',
        category: 'prescriptions',
        tags: ['ocr', 'dispensing', 'verification', 'pharmacist'],
        summary: 'How to scan a paper prescription using OCR and verify it for dispensing.',
        difficulty: 'Intermediate',
        estimatedTime: '3 min',
        roles: ['pharmacist'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/operations/prescription-workflow.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['batches', 'audit-logs'],
    },
    {
        id: 'prescription-ocr-troubleshooting',
        title: 'OCR Troubleshooting & Accuracy Improvement',
        slug: 'operations/prescription-ocr-troubleshooting',
        category: 'prescriptions',
        tags: ['ocr', 'handwriting', 'errors'],
        summary: 'Common OCR issues and how to improve extraction accuracy.',
        difficulty: 'Intermediate',
        estimatedTime: '4 min',
        roles: ['technician', 'pharmacist'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/operations/prescription-ocr-troubleshooting.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['prescription-workflow'],
    },
    {
        id: 'verify-interactions',
        title: 'Drug Interaction & Allergy Checks',
        slug: 'operations/verify-interactions',
        category: 'prescriptions',
        tags: ['safety', 'drug-interaction', 'pharmacist'],
        summary: 'How the system performs interaction checks and what to do when it finds a conflict.',
        difficulty: 'Advanced',
        estimatedTime: '4 min',
        roles: ['pharmacist'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/operations/verify-interactions.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['prescription-workflow', 'audit-logs'],
    },

    // ==================== CUSTOMERS ====================
    {
        id: 'customer-profiles',
        title: 'Customer Profiles & History',
        slug: 'customers/customer-profiles',
        category: 'customers',
        tags: ['crm', 'customer', 'history', 'profile'],
        summary: 'Managing customer data, purchase history, and preferences.',
        difficulty: 'Beginner',
        estimatedTime: '4 min',
        roles: ['cashier', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/customers/customer-profiles.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['loyalty-program', 'data-privacy'],
    },
    {
        id: 'loyalty-program',
        title: 'Loyalty Program Configuration',
        slug: 'customers/loyalty-program',
        category: 'customers',
        tags: ['loyalty', 'points', 'rewards', 'retention'],
        summary: 'Setting up points, tiers, and redemption rules.',
        difficulty: 'Intermediate',
        estimatedTime: '5 min',
        roles: ['manager', 'admin'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/customers/loyalty-program.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['customer-profiles'],
    },

    // ==================== SUPPLIERS ====================
    {
        id: 'create-po',
        title: 'Creating Purchase Orders (PO)',
        slug: 'suppliers/create-po',
        category: 'suppliers',
        tags: ['po', 'procurement', 'supplier', 'ordering'],
        summary: 'Workflow for creating, sending, and tracking purchase orders.',
        difficulty: 'Intermediate',
        estimatedTime: '5 min',
        roles: ['inventory', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/suppliers/create-po.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['reorder-settings', 'receive-stock'],
    },
    {
        id: 'supplier-performance',
        title: 'Supplier Performance & Ratings',
        slug: 'suppliers/supplier-performance',
        category: 'suppliers',
        tags: ['supplier', 'rating', 'performance', 'analytics'],
        summary: 'Evaluating suppliers based on fill rate, lead time, and pricing.',
        difficulty: 'Advanced',
        estimatedTime: '4 min',
        roles: ['manager', 'owner'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/suppliers/supplier-performance.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['create-po'],
    },

    // ==================== REPORTS ====================
    {
        id: 'standard-reports',
        title: 'Standard Reports Overview',
        slug: 'reports/standard-reports',
        category: 'reports',
        tags: ['reports', 'analytics', 'sales', 'profit'],
        summary: 'Guide to the built-in reports: Sales, Inventory, and Financials.',
        difficulty: 'Beginner',
        estimatedTime: '5 min',
        roles: ['manager', 'owner'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/reports/standard-reports.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['custom-reports'],
    },
    {
        id: 'custom-reports',
        title: 'Building Custom Reports',
        slug: 'reports/custom-reports',
        category: 'reports',
        tags: ['reports', 'custom', 'analytics', 'builder'],
        summary: 'How to use the Report Builder to create specific data views.',
        difficulty: 'Advanced',
        estimatedTime: '6 min',
        roles: ['manager', 'analyst'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/reports/custom-reports.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['standard-reports'],
    },
    {
        id: 'expiry-and-aging',
        title: 'Expiry & Aging Analysis',
        slug: 'reports/expiry-and-aging',
        category: 'reports',
        tags: ['expiry', 'aging', 'stock', 'loss-prevention'],
        summary: 'Tracking stock age to prevent losses from expired goods.',
        difficulty: 'Intermediate',
        estimatedTime: '4 min',
        roles: ['inventory', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/reports/expiry-and-aging.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['batches'],
    },

    // ==================== INTEGRATIONS ====================
    {
        id: 'payment-gateway',
        title: 'Payment Gateway Integration',
        slug: 'integrations/payment-gateway',
        category: 'integrations',
        tags: ['payment', 'razorpay', 'stripe', 'card'],
        summary: 'Connecting Razorpay/Stripe/PineLabs for integrated payments.',
        difficulty: 'Intermediate',
        estimatedTime: '5 min',
        roles: ['admin', 'it'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/integrations/payment-gateway.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['pos-sale'],
    },
    {
        id: 'sms-whatsapp',
        title: 'SMS & WhatsApp Notifications',
        slug: 'integrations/sms-whatsapp',
        category: 'integrations',
        tags: ['sms', 'whatsapp', 'notifications', 'marketing'],
        summary: 'Configuring automated messages for invoices, refills, and marketing.',
        difficulty: 'Intermediate',
        estimatedTime: '5 min',
        roles: ['admin', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/integrations/sms-whatsapp.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['customer-profiles'],
    },
    {
        id: 'accounting',
        title: 'Accounting Software Sync (Tally/QuickBooks)',
        slug: 'integrations/accounting',
        category: 'integrations',
        tags: ['accounting', 'tally', 'quickbooks', 'finance'],
        summary: 'Syncing daily sales and purchases to external accounting tools.',
        difficulty: 'Advanced',
        estimatedTime: '6 min',
        roles: ['accountant', 'admin'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/integrations/accounting.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['standard-reports'],
    },

    // ==================== SETTINGS ====================
    {
        id: 'users-roles',
        title: 'User Management & Roles',
        slug: 'settings/users-roles',
        category: 'settings',
        tags: ['users', 'permissions', 'roles', 'security'],
        summary: 'Creating users, assigning roles (Admin/Pharmacist/Cashier), and permissions.',
        difficulty: 'Intermediate',
        estimatedTime: '5 min',
        roles: ['admin'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/settings/users-roles.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['audit-logs'],
    },
    {
        id: 'taxes-gst',
        title: 'Tax Settings & GST Configuration',
        slug: 'settings/taxes-gst',
        category: 'settings',
        tags: ['tax', 'gst', 'vat', 'finance'],
        summary: 'Configuring tax slabs, HSN codes, and composition schemes.',
        difficulty: 'Advanced',
        estimatedTime: '5 min',
        roles: ['admin', 'accountant'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/settings/taxes-gst.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['gst-reports'],
    },
    {
        id: 'store-config',
        title: 'Store Configuration & Preferences',
        slug: 'settings/store-config',
        category: 'settings',
        tags: ['settings', 'config', 'preferences'],
        summary: 'General store settings: currency, time zone, and print preferences.',
        difficulty: 'Beginner',
        estimatedTime: '3 min',
        roles: ['admin'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/settings/store-config.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['receipt-templates'],
    },

    // ==================== COMPLIANCE ====================
    {
        id: 'audit-logs',
        title: 'Audit Logs & Activity Tracking',
        slug: 'compliance/audit-logs',
        category: 'compliance',
        tags: ['audit', 'security', 'logs', 'tracking'],
        summary: 'Viewing the immutable audit trail of all sensitive actions.',
        difficulty: 'Intermediate',
        estimatedTime: '4 min',
        roles: ['admin', 'auditor'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/compliance/audit-logs.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['users-roles'],
    },
    {
        id: 'e-invoicing',
        title: 'e-Invoicing (India GST)',
        slug: 'compliance/e-invoicing',
        category: 'compliance',
        tags: ['gst', 'e-invoice', 'irp', 'compliance'],
        summary: 'Generating IRN and QR codes for B2B transactions > ₹5 Cr turnover.',
        difficulty: 'Advanced',
        estimatedTime: '5 min',
        roles: ['admin', 'accountant'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/compliance/e-invoicing.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['receipt-templates'],
    },
    {
        id: 'data-privacy',
        title: 'Data Privacy & GDPR/DPDP',
        slug: 'compliance/data-privacy',
        category: 'compliance',
        tags: ['privacy', 'gdpr', 'dpdp', 'security'],
        summary: 'Handling patient data, consent, and deletion requests.',
        difficulty: 'Intermediate',
        estimatedTime: '4 min',
        roles: ['admin', 'dpo'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/compliance/data-privacy.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['customer-profiles'],
    },

    // ==================== BILLING (FINANCE) ====================
    {
        id: 'gst-reports',
        title: 'GST Reports (GSTR-1, GSTR-3B)',
        slug: 'billing/gst-reports',
        category: 'billing',
        tags: ['gst', 'tax', 'filing', 'reports'],
        summary: 'Generating monthly GST returns formats.',
        difficulty: 'Intermediate',
        estimatedTime: '4 min',
        roles: ['accountant'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/billing/gst-reports.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['taxes-gst'],
    },
    {
        id: 'credit-notes',
        title: 'Credit Notes & Adjustments',
        slug: 'billing/credit-notes',
        category: 'billing',
        tags: ['credit-note', 'adjustment', 'finance'],
        summary: 'Issuing credit notes for returns or billing errors.',
        difficulty: 'Intermediate',
        estimatedTime: '3 min',
        roles: ['accountant', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/billing/credit-notes.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['returns-credits'],
    },

    // ==================== TROUBLESHOOTING ====================
    {
        id: 'pos-offline-sync',
        title: 'POS Offline Mode & Sync',
        slug: 'troubleshooting/pos-offline-sync',
        category: 'troubleshooting',
        tags: ['offline', 'sync', 'internet', 'pos'],
        summary: 'How to sell without internet and sync later.',
        difficulty: 'Intermediate',
        estimatedTime: '4 min',
        roles: ['cashier', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/troubleshooting/pos-offline-sync.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['pos-sale'],
    },
    {
        id: 'transactions-not-syncing',
        title: 'Transactions Not Syncing?',
        slug: 'troubleshooting/transactions-not-syncing',
        category: 'troubleshooting',
        tags: ['sync', 'error', 'data-loss'],
        summary: 'Steps to resolve stuck transactions or sync errors.',
        difficulty: 'Advanced',
        estimatedTime: '5 min',
        roles: ['admin', 'it'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/troubleshooting/transactions-not-syncing.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['pos-offline-sync'],
    },
    {
        id: 'hardware-issues',
        title: 'Hardware Connection Issues',
        slug: 'troubleshooting/hardware-issues',
        category: 'troubleshooting',
        tags: ['printer', 'scanner', 'usb', 'bluetooth'],
        summary: 'Fixing common printer and scanner connection problems.',
        difficulty: 'Intermediate',
        estimatedTime: '5 min',
        roles: ['it', 'manager'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/troubleshooting/hardware-issues.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['hardware-setup'],
    },

    // ==================== DEVELOPERS ====================
    {
        id: 'api-overview',
        title: 'API Overview & Authentication',
        slug: 'developers/api-overview',
        category: 'developers',
        tags: ['api', 'dev', 'rest', 'auth'],
        summary: 'Introduction to the REST API, authentication, and rate limits.',
        difficulty: 'Advanced',
        estimatedTime: '5 min',
        roles: ['developer'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/developers/api-overview.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['webhooks'],
    },
    {
        id: 'webhooks',
        title: 'Webhooks',
        slug: 'developers/webhooks',
        category: 'developers',
        tags: ['webhooks', 'events', 'realtime'],
        summary: 'Subscribing to real-time events like order.created or inventory.low.',
        difficulty: 'Advanced',
        estimatedTime: '5 min',
        roles: ['developer'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/developers/webhooks.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['api-overview'],
    },
    {
        id: 'sdk-examples',
        title: 'SDK Examples (Node/Python)',
        slug: 'developers/sdk-examples',
        category: 'developers',
        tags: ['sdk', 'code', 'examples'],
        summary: 'Code snippets for common tasks in Node.js and Python.',
        difficulty: 'Advanced',
        estimatedTime: '5 min',
        roles: ['developer'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/developers/sdk-examples.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: ['api-overview'],
    },

    // ==================== OTHER ====================
    {
        id: 'changelog',
        title: 'Changelog',
        slug: 'changelog',
        category: 'other',
        tags: ['updates', 'release-notes'],
        summary: 'Latest features and bug fixes.',
        difficulty: 'Beginner',
        estimatedTime: '2 min',
        roles: ['all'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/changelog.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: [],
    },
    {
        id: 'glossary',
        title: 'Glossary of Terms',
        slug: 'glossary',
        category: 'other',
        tags: ['glossary', 'terms', 'definitions'],
        summary: 'Definitions of common pharmacy and software terms.',
        difficulty: 'Beginner',
        estimatedTime: '5 min',
        roles: ['beginner'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/glossary.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: [],
    },
    {
        id: 'pos-training-playlist',
        title: 'POS Training Playlist',
        slug: 'tutorials/pos-training-playlist',
        category: 'tutorials',
        tags: ['video', 'training', 'staff'],
        summary: 'Curated video tutorials for training new staff.',
        difficulty: 'Beginner',
        estimatedTime: '30 min',
        roles: ['beginner', 'staff'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/tutorials/pos-training-playlist.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: [],
    },
    {
        id: 'terms-of-service',
        title: 'Terms of Service',
        slug: 'legal/terms-of-service',
        category: 'legal',
        tags: ['legal', 'terms'],
        summary: 'Usage agreement for HopeRx software.',
        difficulty: 'Beginner',
        estimatedTime: '10 min',
        roles: ['all'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/legal/terms-of-service.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: [],
    },
    {
        id: 'privacy-policy',
        title: 'Privacy Policy',
        slug: 'legal/privacy-policy',
        category: 'legal',
        tags: ['legal', 'privacy', 'data'],
        summary: 'How we handle your data and your customers\' data.',
        difficulty: 'Beginner',
        estimatedTime: '8 min',
        roles: ['all'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/legal/privacy-policy.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: [],
    },
    {
        id: 'contribute',
        title: 'Contribute to Docs',
        slug: 'contribute',
        category: 'other',
        tags: ['community', 'edit', 'feedback'],
        summary: 'How to suggest edits or add new articles.',
        difficulty: 'Intermediate',
        estimatedTime: '2 min',
        roles: ['all'],
        lastUpdated: '2025-11-24',
        contributors: ['HopeRx Team'],
        content: '',
        markdownPath: '/docs/contribute.md',
        steps: [],
        troubleshooting: [],
        relatedArticles: [],
    },
];

export function getArticleById(id: string): DocArticle | undefined {
    return ARTICLES.find(article => article.id === id);
}

export function getArticlesByCategory(categoryId: string): DocArticle[] {
    return ARTICLES.filter(article => article.category === categoryId);
}

export function getPopularArticles(limit: number = 5): DocArticle[] {
    // Return first N articles for now, or implement logic based on views/rating
    return ARTICLES.slice(0, limit);
}
