export const demoMedicines = [
    { id: 1, name: "Dolo 650 Tablet", price: 30, pack: "strip of 15 tablets", composition: "Paracetamol (650mg)" },
    { id: 2, name: "Azithral 500 Tablet", price: 132, pack: "strip of 5 tablets", composition: "Azithromycin (500mg)" },
    { id: 3, name: "Pan D Capsule", price: 150, pack: "strip of 10 capsules", composition: "Pantoprazole (40mg), Domperidone (10mg)" },
    { id: 4, name: "Augmentin 625 Duo Tablet", price: 223, pack: "strip of 10 tablets", composition: "Amoxycillin (500mg), Clavulanic Acid (125mg)" },
    { id: 5, name: "Ascoril LS Syrup", price: 118, pack: "bottle of 100 ml", composition: "Ambroxol (30mg/5ml), Levosalbutamol (1mg/5ml)" },
    { id: 6, name: "Allegra 120mg Tablet", price: 219, pack: "strip of 10 tablets", composition: "Fexofenadine (120mg)" },
    { id: 7, name: "Avil 25 Tablet", price: 11, pack: "strip of 15 tablets", composition: "Pheniramine (25mg)" },
    { id: 8, name: "Azee 500 Tablet", price: 132, pack: "strip of 5 tablets", composition: "Azithromycin (500mg)" },
    { id: 9, name: "Atarax 25mg Tablet", price: 86, pack: "strip of 15 tablets", composition: "Hydroxyzine (25mg)" },
    { id: 10, name: "Crocin Advance Tablet", price: 25, pack: "strip of 15 tablets", composition: "Paracetamol (500mg)" },
    { id: 11, name: "Aciloc 150 Tablet", price: 41, pack: "strip of 30 tablets", composition: "Ranitidine (150mg)" },
    { id: 12, name: "Alex Syrup", price: 129, pack: "bottle of 100 ml", composition: "Phenylephrine (5mg/5ml), Chlorpheniramine (2mg/5ml)" },
    { id: 13, name: "Almox 500 Capsule", price: 80, pack: "strip of 10 capsules", composition: "Amoxycillin (500mg)" },
    { id: 14, name: "Asthalin Inhaler 100mcg", price: 158, pack: "packet of 200 MDI", composition: "Salbutamol (100mcg)" },
    { id: 15, name: "Brufen 400 Tablet", price: 18, pack: "strip of 15 tablets", composition: "Ibuprofen (400mg)" },
    { id: 16, name: "Cetirizine 10mg Tablet", price: 15, pack: "strip of 10 tablets", composition: "Cetirizine (10mg)" },
    { id: 17, name: "Combiflam Tablet", price: 22, pack: "strip of 20 tablets", composition: "Ibuprofen (400mg), Paracetamol (325mg)" },
    { id: 18, name: "Disprin Tablet", price: 8, pack: "strip of 10 tablets", composition: "Aspirin (325mg)" },
    { id: 19, name: "Electral Powder", price: 21, pack: "sachet of 21.8 gm", composition: "Dextrose, Sodium Chloride, Potassium Chloride" },
    { id: 20, name: "Flexon Tablet", price: 12, pack: "strip of 15 tablets", composition: "Paracetamol (325mg), Ibuprofen (400mg)" },
    { id: 21, name: "Gelusil Syrup", price: 95, pack: "bottle of 200 ml", composition: "Aluminium Hydroxide, Magnesium Hydroxide" },
    { id: 22, name: "Glycomet 500 SR", price: 28, pack: "strip of 20 tablets", composition: "Metformin (500mg)" },
    { id: 23, name: "Metrogyl 400 Tablet", price: 12, pack: "strip of 15 tablets", composition: "Metronidazole (400mg)" },
    { id: 24, name: "Montair LC Tablet", price: 95, pack: "strip of 10 tablets", composition: "Montelukast (10mg), Levocetirizine (5mg)" },
    { id: 25, name: "Norflox TZ Tablet", price: 56, pack: "strip of 10 tablets", composition: "Norfloxacin (400mg), Tinidazole (600mg)" },
    { id: 26, name: "ORS Powder", price: 8, pack: "sachet of 20 gm", composition: "Oral Rehydration Salts" },
    { id: 27, name: "Paracetamol 500mg Tablet", price: 18, pack: "strip of 15 tablets", composition: "Paracetamol (500mg)" },
    { id: 28, name: "Pantocid 40 Tablet", price: 115, pack: "strip of 15 tablets", composition: "Pantoprazole (40mg)" },
    { id: 29, name: "Rabipur Vaccine", price: 325, pack: "vial of 1 ml", composition: "Rabies Vaccine" },
    { id: 30, name: "Sinarest Tablet", price: 14, pack: "strip of 10 tablets", composition: "Paracetamol (500mg), Phenylephrine (10mg)" },
    { id: 31, name: "Telma 40 Tablet", price: 92, pack: "strip of 15 tablets", composition: "Telmisartan (40mg)" },
    { id: 32, name: "Vicks Vaporub", price: 68, pack: "jar of 50 ml", composition: "Camphor, Menthol, Eucalyptus Oil" },
    { id: 33, name: "Zincovit Tablet", price: 110, pack: "strip of 15 tablets", composition: "Multivitamin with Zinc" },
    { id: 34, name: "Betadine Solution", price: 82, pack: "bottle of 100 ml", composition: "Povidone Iodine (10%)" },
    { id: 35, name: "Cetaphil Gentle Cleanser", price: 245, pack: "bottle of 125 ml", composition: "Cleansing Lotion" },
    { id: 36, name: "Livogen Tablet", price: 92, pack: "strip of 15 tablets", composition: "Iron, Folic Acid" },
    { id: 37, name: "Omnacortil 10 Tablet", price: 52, pack: "strip of 10 tablets", composition: "Prednisolone (10mg)" },
    { id: 38, name: "Supradyn Daily Tablet", price: 215, pack: "strip of 15 tablets", composition: "Multivitamin, Multimineral" },
    { id: 39, name: "Wikoryl Tablet", price: 18, pack: "strip of 10 tablets", composition: "Paracetamol (500mg), Phenylephrine (10mg)" },
    { id: 40, name: "Zyrtec 10mg Tablet", price: 78, pack: "strip of 10 tablets", composition: "Cetirizine (10mg)" },
    { id: 41, name: "Amoxyclav 625 Tablet", price: 223, pack: "strip of 10 tablets", composition: "Amoxycillin (500mg), Clavulanic Acid (125mg)" },
    { id: 42, name: "Calpol 650 Tablet", price: 28, pack: "strip of 15 tablets", composition: "Paracetamol (650mg)" },
    { id: 43, name: "Limcee 500mg Tablet", price: 22, pack: "strip of 15 tablets", composition: "Vitamin C (500mg)" },
    { id: 44, name: "Neurobion Forte Tablet", price: 32, pack: "strip of 10 tablets", composition: "Vitamin B Complex" },
    { id: 45, name: "Shelcal 500 Tablet", price: 92, pack: "strip of 15 tablets", composition: "Calcium (500mg), Vitamin D3 (250IU)" },
    { id: 46, name: "Wysolone 10 Tablet", price: 55, pack: "strip of 15 tablets", composition: "Prednisolone (10mg)" },
    { id: 47, name: "Cough Syrup", price: 65, pack: "bottle of 100 ml", composition: "Guaifenesin, Bromhexine" },
    { id: 48, name: "Dettol Antiseptic Liquid", price: 85, pack: "bottle of 125 ml", composition: "Chloroxylenol (4.8%)" },
    { id: 49, name: "Moov Pain Relief Spray", price: 112, pack: "bottle of 80 gm", composition: "Diclofenac (1.16%)" },
    { id: 50, name: "Strepsils Lozenges", price: 32, pack: "strip of 8 lozenges", composition: "Amylmetacresol, Dichlorobenzyl" }
];
